---
#
# This playbook will read the ports.yaml file in the same directory and configure the ports
# on the specified switch serial number in the Meraki cloud
#
- name: meraki query
  hosts: meraki
  vars:
    auth_key: "{{ auth }}"
    org_name: "{{ org }}"

  tasks:

    - name: include variables for devices
      ansible.builtin.include_vars:
        file: ports.yaml

    - name: Query Organization
      cisco.meraki.meraki_organization:
        auth_key: "{{ auth_key }}"
        org_name: "{{ org_name }}"
        state: query
      register: org_output

    - name: Add devices to Network
      cisco.meraki.meraki_switchport:
        auth_key: "{{ auth_key }}"
        org_id: "{{ org_output.data.id }}"
        state: present
        serial: "{{ item.serial }}"
        number: "{{ item.number }}"
        enabled: true
        name: "{{ item.name }}"
        type: "{{ item.type | lower }}"
        vlan: "{{ item.vlan }}"
        access_policy_number: "{{ item.access_policy_number | default(omit) }}"
        access_policy_type: "{{ item.access_policy_type }}"
        allowed_vlans: "{{ item.allowed_vlans }}"
        tags: "{{ item.tags }}"
        stp_guard: "{{ item.stp_guard | lower }}"
        poe_enabled: "{{ item.poe_enabled }}"
      loop: "{{ ports }}"
