---
# Run with: DO NOT run this individually. It is called by query-and-add-devices.yml
#
# This playbook will read the devices.yaml file in the same directory and add the device specified at runtime to
# the Network listed in the site_name field on Meraki Cloud
#
- name: include variables for devices
  ansible.builtin.include_vars:
    file: ports.yaml
    name: ports

# - name: Select device to add 
#   ansible.builtin.set_fact:
#     new_device: "{{ devices.devices | json_query(jmesquery) }}"
#   vars:
#     jmesquery: "[?device_name=='{{ item }}']"

# - name: Adding new device
#   ansible.builtin.debug:
#     msg: "Adding device {{ new_device[0].device_name }} to network {{ new_device[0].network_name }}"

- name: Query Organization
  cisco.meraki.meraki_organization:
    auth_key: "{{ auth_key }}"
    org_name: "{{ org_name }}"
    state: query
  register: org_output

- name: Add devices to Network
  cisco.meraki.meraki_switchport:
    auth_key: "{{ auth_key }}"
    org_id: "{{ org_output.data.id }}"
    # net_name: "{{ new_device[0].network_name }}"
    state: present
    serial: "{{ item.switch_serial_no }}"
    number: "{{ item.port_number }}"
    enabled: true
    name: "{{ item.name }}"
    type: "{{ item.type }}"
    vlan: "{{ item.vlan }}"
    access_policy_number: 1
    allowed_vlans: "{{ item.allowed_vlans }}"
    tags: "{{ item.tags }}"
    stp_guard: "{{ item.stp_guard | lower }}"
    poe_enabled: "{{ item.poe_enabled }}"
  with_items: "{{ ports }}"
  # register: off_add_dev1

# - name: Update device Information
#   cisco.meraki.meraki_device:
#     auth_key: "{{ auth_key }}"
#     org_id: "{{ org_output.data.id }}"
#     net_name: "{{ new_device[0].network_name }}"
#     state: present
#     serial: "{{ new_device[0].serial_no }}"
#     hostname: "{{ new_device[0].device_name }}"
#     address: "{{ new_device[0].site_address }}"
#     move_map_marker: true
#   register: off_update_dev1
