---
#
# This playbook will read the ports.yaml file in the same directory and configure the ports
# on the specified switch serial number in the Meraki cloud
#
- name: meraki query
  hosts: meraki
  vars:
    auth_key: "{{ auth }}"
    org_name: "{{ org }}"

  tasks:

    - name: include variables for devices
      ansible.builtin.include_vars:
        file: ports.yaml

    - name: Query Organization
      cisco.meraki.meraki_organization:
        auth_key: "{{ auth_key }}"
        org_name: "{{ org_name }}"
        state: query
      register: org_output

    - name: Add devices to Network
      cisco.meraki.meraki_switchport:
        auth_key: "{{ auth_key }}"
        org_id: "{{ org_output.data.id }}"
        state: present
        serial: "{{ item.S_N }}"
        number: "{{ item.Meraki_Port }}"
        enabled: true
        name: "{{ item.Name }}"
        type: "{{ item.Access_Trunk | lower }}"
        vlan: "{{ item.Access_Native_VLAN }}"
        access_policy_number: "{{ item.access_policy_number | default(omit) }}"
        access_policy_type: "{{ item.access_policy_type }}"
        allowed_vlans: "{{ item.Tagged_VLANs }}"
        tags: "{{ item.Port_Tag }}"
        stp_guard: "{{ item.STP_guard | lower }}"
        poe_enabled: "{{ item.poe_enabled }}"
      loop: "{{ ports }}"
