---
# Run with: ansible-playbook -i inventories/hosts query-sites.yml
#
# This playbook will query the user for what network name they want to check Meraki Cloud for
# You can choose to enter a specific name to search for or leave it blank and it will display all of the networks
# It will error out if the network has not been created yet
# If successful, it will either display a list of all Networks in the Org or
# it will display a list of devices attached to the network specified
#
- name: meraki query
  hosts: meraki
  vars:
    auth_key: "{{ auth }}"
    org_name: "{{ org }}"

  vars_prompt:

    - name: switch_serial_no
      prompt: "What switch serial number do you want to see the ports for? "
      private: no 

  tasks:

    - name: Query Organization
      cisco.meraki.meraki_organization:
        auth_key: "{{ auth_key }}"
        org_name: "{{ org_name }}"
        state: query
      register: org_output

    - name: Query all ports on switch SN 
      cisco.meraki.meraki_switchport:
        auth_key: "{{ auth_key }}"
        org_name: "{{ org_name }}"
        state: query
        serial: "{{ switch_serial_no }}"
      register: ports_output

    - name: Print ports_output
      ansible.builtin.debug:
        var: ports_output
